sbatch submit_01.sjob
sbatch submit_02.sjob
sbatch submit_03.sjob
sbatch submit_04.sjob
sbatch submit_05.sjob
sbatch submit_06.sjob
sbatch submit_07.sjob
sbatch submit_08.sjob
sbatch submit_09.sjob
sbatch submit_10.sjob
sbatch submit_11.sjob
